[[scheduled]]
cron = "0 3 * * *"
command = "curl -X GET https://minimodels.com.pl/api/cleanup -H 'x-cleanup-secret: bnAgvgMWrhdtpueCENerCcZdmnHUemyKNurKpeQPfCbVJPAqcmcDaTYcEtpus9kMMrjcSbEQajCu944Xjy22WM9hH7o9gvez2LEY3XEgVDzFZCzrrUwhKdjxeVyTbpiE'"