/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type ModelCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "modelCategory";
};

export type Model = {
  _id: string;
  _type: "model";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  category: ModelCategoryReference;
  birthDate: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  eyeColor?: "blue" | "green" | "brown" | "grey" | "hazel";
  hairColor?:
    | "light-blonde"
    | "blonde"
    | "dark-blonde"
    | "brown"
    | "black"
    | "red";
  hairLength?: "short" | "medium" | "long";
  hairType?: "straight" | "wavy" | "curly";
  active?: boolean;
  contractDate?: string;
};

export type ModelCategory = {
  _id: string;
  _type: "modelCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: "baby" | "mini-girls" | "mini-boys" | "teens";
  slug: Slug;
  inMenu?: boolean;
  displayName?: {
    pl: string;
    en: string;
  };
  seo_pl?: {
    title?: string;
    description?: string;
    keywords?: Array<string>;
  };
  seo_en?: {
    title?: string;
    description?: string;
    keywords?: Array<string>;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo_pl?: {
    seoTitle?: string;
    seoDescription?: string;
    seoKeywords?: Array<string>;
  };
  seo_en?: {
    seoTitle?: string;
    seoDescription?: string;
    seoKeywords?: Array<string>;
  };
  sections?: Array<{
    sectionTitle: string;
    texts?: {
      pl?: Array<string>;
      en?: Array<string>;
    };
    backgroundImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: {
        pl?: string;
        en?: string;
      };
      _type: "image";
    };
    pictures?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: {
        pl?: string;
        en?: string;
      };
      _type: "image";
      _key: string;
    }>;
    button?: {
      label?: {
        pl?: string;
        en?: string;
      };
      url?: string;
    };
    videoUrl?: string;
    _type: "section";
    _key: string;
  }>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AuthorReference
  | SanityImageAssetReference
  | CategoryReference
  | Post
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | Category
  | ModelCategoryReference
  | Model
  | ModelCategory
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: BABIES_QUERY
// Query: *[_type == "model"     && category->title == "baby"     && active == true    && defined(contractDate)    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)  ] | order(birthDate desc) {    _id, name, slug, birthDate, profileImage, "category": category->title  }
export type BABIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  birthDate: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: "baby" | "mini-boys" | "mini-girls" | "teens";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MINIBOYS_QUERY
// Query: *[_type == "model"    && category->title == "mini-boys"    && active == true    && defined(contractDate)    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {  _id, name, slug, birthDate, profileImage, "category": category->title}
export type MINIBOYS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  birthDate: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: "baby" | "mini-boys" | "mini-girls" | "teens";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MINIGIRLS_QUERY
// Query: *[_type == "model"    && category->title == "mini-girls"    && active == true    && defined(contractDate)    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {  _id, name, slug, birthDate, profileImage, "category": category->title}
export type MINIGIRLS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  birthDate: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: "baby" | "mini-boys" | "mini-girls" | "teens";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TEENS_QUERY
// Query: *[_type == "model"    && category->title == "teens"    && active == true    && defined(contractDate)    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {  _id, name, slug, birthDate, profileImage, "category": category->title}
export type TEENS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  birthDate: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: "baby" | "mini-boys" | "mini-girls" | "teens";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MODEL_QUERY
// Query: *[_type == "model" && slug.current == $slug][0] {  name,  birthDate,  "category": category->slug.current,  profileImage, gallery[defined(asset)] {  asset-> {    _id,    url,    alt,    metadata {      dimensions {        width,        height,        aspectRatio      }    }  },  _key,  _type,  alt}, eyeColor, hairColor, hairLength, hairType}
export type MODEL_QUERY_RESULT = {
  name: string;
  birthDate: string;
  category: string;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery: Array<{
    asset: {
      _id: string;
      url: string;
      alt: null;
      metadata: {
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    };
    _key: string;
    _type: "image";
    alt: string | null;
  }> | null;
  eyeColor: "blue" | "brown" | "green" | "grey" | "hazel" | null;
  hairColor:
    | "black"
    | "blonde"
    | "brown"
    | "dark-blonde"
    | "light-blonde"
    | "red"
    | null;
  hairLength: "long" | "medium" | "short" | null;
  hairType: "curly" | "straight" | "wavy" | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MODEL_SIBLINGS_QUERY
// Query: {    "next": *[_type == "model"       && category->slug.current == $category       && active == true      && defined(contractDate)      && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)      && birthDate < $birthDate    ] | order(birthDate desc)[0] {      name,      slug,      profileImage    },    "prev": *[_type == "model"      && category->slug.current == $category      && active == true      && defined(contractDate)      && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)      && birthDate > $birthDate    ] | order(birthDate asc)[0] {      name,      slug,      profileImage    }  }
export type MODEL_SIBLINGS_QUERY_RESULT = {
  next: {
    name: string;
    slug: Slug;
    profileImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  } | null;
  prev: {
    name: string;
    slug: Slug;
    profileImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  } | null;
};

// Source: src/sanity/lib/queries.ts
// Variable: ALL_BABY_SLUGS_QUERY
// Query: *[_type == "model" && category->title == "baby" && active == true && defined(slug.current)] {    "slug": slug.current  }
export type ALL_BABY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_MINIBOYS_SLUGS_QUERY
// Query: *[_type == "model" && category->title == "mini-boys" && active == true && defined(slug.current)] {    "slug": slug.current  }
export type ALL_MINIBOYS_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_MINIGIRLS_SLUGS_QUERY
// Query: *[_type == "model" && category->title == "mini-girls" && active == true && defined(slug.current)] {    "slug": slug.current  }
export type ALL_MINIGIRLS_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_TEENS_SLUGS_QUERY
// Query: *[_type == "model" && category->title == "teens" && active == true && defined(slug.current)] {    "slug": slug.current  }
export type ALL_TEENS_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MENU_MODEL_CATEGORIES_QUERY
// Query: *[_type == "modelCategory" && inMenu == true] | order(title asc) {    _id,    inMenu,    "slug": slug.current,    "displayName": displayName  }
export type MENU_MODEL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  inMenu: true;
  slug: string;
  displayName: {
    pl: string;
    en: string;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MODEL_CATEGORIES_QUERY
// Query: *[_type == "modelCategory" && title == $category][0] {    title,    "seo": seo_pl, // lub dynamicznie    "seoTitle": select(      $locale == "pl" => seo_pl.title,      $locale == "en" => seo_en.title,    ),    "seoDescription": select(      $locale == "pl" => seo_pl.description,      $locale == "en" => seo_en.description,    ),    "seoKeywords": select(      $locale == "pl" => seo_pl.keywords,      $locale == "en" => seo_en.keywords,    ),  }
export type MODEL_CATEGORIES_QUERY_RESULT = {
  title: "baby" | "mini-boys" | "mini-girls" | "teens";
  seo: {
    title?: string;
    description?: string;
    keywords?: Array<string>;
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoKeywords: Array<string> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0] {    title,    sections[] {      sectionTitle,      texts,      backgroundImage {        asset-> {          url,          metadata {            dimensions {              width,              height            }          }        },        alt      },      pictures[] {        asset-> {          url,          metadata {            dimensions {              width,              height            }          }        },        alt      },      button,      videoUrl    }  }
export type HOME_PAGE_QUERY_RESULT = {
  title: string | null;
  sections: Array<{
    sectionTitle: string;
    texts: {
      pl?: Array<string>;
      en?: Array<string>;
    } | null;
    backgroundImage: {
      asset: {
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: {
        pl?: string;
        en?: string;
      } | null;
    };
    pictures: Array<{
      asset: {
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: {
        pl?: string;
        en?: string;
      } | null;
    }> | null;
    button: {
      label?: {
        pl?: string;
        en?: string;
      };
      url?: string;
    } | null;
    videoUrl: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "model" \n    && category->title == "baby" \n    && active == true\n    && defined(contractDate)\n    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)\n  ] | order(birthDate desc) {\n    _id, name, slug, birthDate, profileImage, "category": category->title\n  }\n': BABIES_QUERY_RESULT;
    '*[_type == "model"\n    && category->title == "mini-boys"\n    && active == true\n    && defined(contractDate)\n    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {\n  _id, name, slug, birthDate, profileImage, "category": category->title\n}': MINIBOYS_QUERY_RESULT;
    '*[_type == "model"\n    && category->title == "mini-girls"\n    && active == true\n    && defined(contractDate)\n    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {\n  _id, name, slug, birthDate, profileImage, "category": category->title\n}': MINIGIRLS_QUERY_RESULT;
    '*[_type == "model"\n    && category->title == "teens"\n    && active == true\n    && defined(contractDate)\n    && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)] | order(birthDate desc) {\n  _id, name, slug, birthDate, profileImage, "category": category->title\n}': TEENS_QUERY_RESULT;
    '*[_type == "model" && slug.current == $slug][0] {\n  name,\n  birthDate,\n  "category": category->slug.current,\n  profileImage, gallery[defined(asset)] {\n  asset-> {\n    _id,\n    url,\n    alt,\n    metadata {\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  _key,\n  _type,\n  alt\n}, eyeColor, hairColor, hairLength, hairType\n}': MODEL_QUERY_RESULT;
    '\n  {\n    "next": *[_type == "model" \n      && category->slug.current == $category \n      && active == true\n      && defined(contractDate)\n      && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)\n      && birthDate < $birthDate\n    ] | order(birthDate desc)[0] {\n      name,\n      slug,\n      profileImage\n    },\n    "prev": *[_type == "model"\n      && category->slug.current == $category\n      && active == true\n      && defined(contractDate)\n      && dateTime(contractDate + "T00:00:00Z") > dateTime($cutoffDate)\n      && birthDate > $birthDate\n    ] | order(birthDate asc)[0] {\n      name,\n      slug,\n      profileImage\n    }\n  }\n': MODEL_SIBLINGS_QUERY_RESULT;
    '*[_type == "model" && category->title == "baby" && active == true && defined(slug.current)] {\n    "slug": slug.current\n  }': ALL_BABY_SLUGS_QUERY_RESULT;
    '*[_type == "model" && category->title == "mini-boys" && active == true && defined(slug.current)] {\n    "slug": slug.current\n  }': ALL_MINIBOYS_SLUGS_QUERY_RESULT;
    '*[_type == "model" && category->title == "mini-girls" && active == true && defined(slug.current)] {\n    "slug": slug.current\n  }': ALL_MINIGIRLS_SLUGS_QUERY_RESULT;
    '*[_type == "model" && category->title == "teens" && active == true && defined(slug.current)] {\n    "slug": slug.current\n  }': ALL_TEENS_SLUGS_QUERY_RESULT;
    '\n  *[_type == "modelCategory" && inMenu == true] | order(title asc) {\n    _id,\n    inMenu,\n    "slug": slug.current,\n    "displayName": displayName\n  }\n': MENU_MODEL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "modelCategory" && title == $category][0] {\n    title,\n    "seo": seo_pl, // lub dynamicznie\n    "seoTitle": select(\n      $locale == "pl" => seo_pl.title,\n      $locale == "en" => seo_en.title,\n    ),\n    "seoDescription": select(\n      $locale == "pl" => seo_pl.description,\n      $locale == "en" => seo_en.description,\n    ),\n    "seoKeywords": select(\n      $locale == "pl" => seo_pl.keywords,\n      $locale == "en" => seo_en.keywords,\n    ),\n  }\n': MODEL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0] {\n    title,\n    sections[] {\n      sectionTitle,\n      texts,\n      backgroundImage {\n        asset-> {\n          url,\n          metadata {\n            dimensions {\n              width,\n              height\n            }\n          }\n        },\n        alt\n      },\n      pictures[] {\n        asset-> {\n          url,\n          metadata {\n            dimensions {\n              width,\n              height\n            }\n          }\n        },\n        alt\n      },\n      button,\n      videoUrl\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
  }
}
