export const BOT_PATTERNS = [
  "bot",
  "crawl",
  "spider",
  "slurp",
  "curl",
  "wget",
  "python-requests",
  "facebookexternalhit",
  "mediapartners-google",
  "bingpreview",
  "twitterbot",
  "linkedinbot",
  "embedly",
  "quora link preview",
  "showyoubot",
  "outbrain",
  "pinterest/0.",
  "developers.google.com/+/web/snippet",
  "googlebot",
];
